modLoader="javafml"
loaderVersion="[40,)"
license="Public Domain"

[[mods]]
modId="poisonpotatopotion"
version="1.0.0"
displayName="Poison Potato Potion"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://modrinth.com/user/VegaKey"
authors="VegaKey"
description="Adds the ability to brew poison potatos into Potions"

[[dependencies.poisonpotatopotion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




